# Use root/example as user/password credentials
version: '3.1'

services:

###############  ORDER SERVICE ###################
  postgre_order:
    image: postgres
    container_name: postresql_order_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_order
      - POSTGRES_USER=root_ion
      - POSTGRES_PASSWORD=secret_order

  order-service:
    image: order-service
    container_name: order-service-container
    restart: unless-stopped
    build:
      context: order-service
      dockerfile: Dockerfile
    ports:
      - "8079:8079"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgre_order:5432/postgres_order
      - SPRING_DATASOURCE_USERNAME=root_ion
      - SPRING_DATASOURCE_PASSWORD=secret_order
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgre_order
      - discovery-server
##################################################

##############  PRODUCT SERVICE ##################
  mongo:
    image: mongo
    container_name: mongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: products
      MONGO_INITDB_ROOT_USERNAME: root_ion
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "30007:27017"

  mongo-express:
    image: mongo-express
    container_name: mongoDB_express
    restart: unless-stopped
    ports:
      - 6082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongoDB
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root_ion
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
  
  product-service:
    image: product-service
    container_name: product-service-container
    build:
      context: product-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo
      - discovery-server
##################################################



#############  INVENTORY SERVICE #################
  postgre_inventory:
    image: postgres
    container_name: postresql_inventory_container
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=root_ion
      - POSTGRES_PASSWORD=secret_inventory

  inventory-service:
    image: inventory-service
    container_name: inventory-service-container
    restart: unless-stopped
    build:
      context: inventory-service
      dockerfile: Dockerfile
    ports:
      - "8078:8078"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgre_inventory:5432/inventory
      - SPRING_DATASOURCE_USERNAME=root_ion
      - SPRING_DATASOURCE_PASSWORD=secret_inventory
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgre_inventory
      - discovery-server
##################################################



##############  DISCOVERY SERVER #################
  discovery-server:
    image: eureka-discovery
    container_name: eureka-discovery-container
    restart: unless-stopped
    build:
      context: discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
##################################################