# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongoDB_express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  #service 2: definition of your spring-boot app 
  product-service:                        #it is just a name, which will be used only in this file.
    image: product-service               #name of the image after dockerfile executes
    container_name: product-service-container  #name of the container created from docker image
    build:
      context: product-service                #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8079:8079"                       #docker containter port with your os port
    restart: unless-stopped  
    depends_on:                           #define dependencies of this app
      - mongo                             #dependency name (which is defined with this name 'db' in this file earlier)
  
  PostgreSQL:
    image: postgres
    container_name: postresql_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  order-service:
    image: order-service
    container_name: order-service-container
    restart: unless-stopped
    build:
      context: order-service                #docker file path (. means root directory)
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - PostgreSQL